openapi: 3.0.1
info:
  title: Workleap Extensions XUnit
  description: .NET library providing fixtures for unit tests and integration tests.
  x-cortex-git:
    github:
      alias: gsoft-inc
      repository: gsoft-inc/wl-extensions-xunit
  x-cortex-tag: service-wl-extensions-xunit
  x-cortex-type: library
  x-cortex-slack:
    channels:
      - name: internal-dev-platform
        notificationsEnabled: true
  x-cortex-owners:
    - name: team-internal-developer-platform-backend
      type: GROUP
      provider: CORTEX
  x-cortex-link:
    - name: Documentation
      type: documentation
      url: https://gsoftdev.atlassian.net/wiki/spaces/TEC/pages/3454271503
    - type: cortex
      url: https://github.com/gsoft-inc/wl-extensions-xunit/blob/main/.cortex/catalog/service-wl-extensions-xunit.yaml
      name: Edit current Cortex entity in GitHub

